post: &post
  boxsize: {height: 192, width: 128}
  points_exclude: [4, 5, 6, 7]
  link_sequence: [[0, 1, 1, 2, 3, 4, 5, 6, 7],
                  [1, 2, 3, 4, 5, 6, 7, 8, 9]]
  background_index: [0]
  heatmap_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

data:
  dataloader:
    train:
      batch_size: 1
      num_workers: 1
      shuffle: true
    valid:
      batch_size: 1
      num_workers: 4
      shuffle: true
    test:
      batch_size: 1
      num_workers: 4
      shuffle: true

  dataset:
    defaults: &defaults
      root: '/home/ys/Data/data_reognized_20180910'
      image_size: {height: 192, width: 128}
      enable_fourth_channel: true
      keypoints_list: [0, 1, 2, 3, 8, 9, 10, 11, 12, 13]
      keypoints_names: ['head', 'neck', 'right_shoulder', 'left_shoulder', 'right_hip', 'left_hip', 'right_knee',
       'left_knee', 'right_ankle', 'left_ankle']
      heatmap_stride: 2

    train:
      relative_txt_path: 'txt/multiple_txt_files_mode/20180910_example/train/20180910_train_pointer.txt'
      txt_path:
      fourth_channel_prob: 0.8  # valid when enable_fourth_channel is True, ensure that fourth channel has some probabilities to be fully black
      enable_generate_fake_fourth_channel: False  # generate fourth channel for image data which has no real last frame data
      fourth_channel_keypoint_position_jitter_pixels: 5  # for last frame keypoints jitter
      fourth_channel_keypoint_vis_status_jitter_prob: 0.3
      fourth_channel_heatmap_sigma: 4.0
      heatmap_visible_level: 2
      heatmap_sigma: [4.0]
      enable_cross_body_crop: True
      cross_body_crop_probs: [0.3, 0.3, 0.4] # [upper half, lower half, do nothing], must sums to 1
      crop_width: 128   # for cropping image patch from gt bbox
      crop_height: 192
      crop_min_size: 1.0
      crop_max_size: 3.5
      rotate: 5
      scale: {min: 0.9, max: 1.1}
      center_perturb_max: 20
      <<: *defaults
      <<: *post

    valid:
      relative_txt_path: 'txt/multiple_txt_files_mode/20180910_example/valid/valid.txt'
      txt_path:
#      video_path: '/root/group-pose-estimation/video_test_selected_20180608/NoNeedRotate/'
      video_path: '/home/ys/Data/pose_estimate_test/video_test_selected_20180608/NoNeedRotate/'
      fourth_channel_heatmap_sigma: 4.0
      heatmap_visible_level: 2
      heatmap_sigma: [4.0]
      crop_width: 128   # for cropping image patch from gt bbox
      crop_height: 192
      crop_min_size: 1.0
      crop_max_size: 1.0
      <<: *defaults
      <<: *post

model:
  output_type: 'heatmap'
  out_h: 100
  out_w: 64
  out_c: 10
  fourth_channel: false
  pyramid_num: 4

loss:
  global_weight: 1
  refine_weight: 1
  top_k: 6

optim:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

train:
  epochs: 20
  log_interval: 10
  save_model_interval: 1
  valid_interval: 1

save:
  gear_save_root: '/home/ys/Data/pose_estimate_save/'
  root:
  relative_model: 'models'
  relative_train: 'train'
  relative_valid: 'valid'
  relative_analyze: 'valid/coco_analyze'
  relative_tensorboard: 'tensorboard'
  relative_test: 'tst'
  model:
  train:
  valid:
  analyze:
  tensorboard:
  test:

device: 'cuda'
device_ids: [0]

tensorboard:
  enable: true

visdom:
  enable: false
  server: 'http://localhost'
  port: 8097

image_site:
  enable: false
  url: 'http://172.16.3.247:8000/image-site/dataset/{dataset_name}?size=50&page=1'
  data_dir: '/root/group-mtlab-bj/image_site_datasets'

